### ISSUE TITLE
Missing documentation on channel open fees when receiving a payment

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk-docs#109]
https://sdk-doc.breez.technology/guide/receive_payment.html

Receiving a payment requires you to communicate the potential channel open fees to the user. We have no recommendations for this in the docs.

![](https://files.slack.com/files-pri/T01SU6F722H-F069HRL1G3D/screen_shot_2023-12-11_at_9.16.32_am.png)

**Comment by ok300** [comment]
Fixed with https://github.com/breez/breez-sdk-docs/pull/122
