### ISSUE TITLE
On-chain operations assume a baseline knowledge of submarine swaps

### ISSUE THREAD

**Issue by rustaceanrob** [breez/breez-sdk-docs#113]
I was unaware of the nomenclature of submarine swaps before working with the SDK. I think it is fair to assume some developers will come from a non-LN background and might find this confusing. A potential revision would be an introduction to submarine swap-ins and outs prior to diving into receiving and sending on-chain. 

- 5 submarine swaps
     - 5.1 receive
     - 5.2 send

I can start working on this in the evenings if the maintainers agree.

**Comment by ok300** [comment]
Hey @rustaceanrob thanks for the feedback.

The nomenclature around swaps went through several iterations, it's now
 - Receive an on-chain tx (Swap-in): https://sdk-doc.breez.technology/guide/receive_onchain.html
 - Send an on-chain tx (Swap-out): https://sdk-doc.breez.technology/guide/send_onchain.html

We tried to include a concise description of what it's happening ("send / receive on-chain tx") as well as the simplified swap title ("swap-in / swap-out").

It's useful to look at it from the perspective of LN. Thus:
- swap-in = "swap-into-LN", e.g. the direction is from on-chain to LN
- swap-out = "swap-out-of-LN", e.g. the direction is from LN to on-chain

Would you say the doc links above are clear enough on this?

**Comment by rustaceanrob** [comment]
Yes the base case and alternative results are quite clear now. Thanks for the update!
