### ISSUE TITLE
Use a single instance of BreezSDK on Dart documentation

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk-docs#145]
Getting reports of users running into this exception.
```
Exception: Subclasses of
'FlutterRustBBreezSdkCorePlatform singletons - there should not be two instances
(runtimeType=BreezSdkCorePlatform)
```
and this syntax: `await BreezSDK().apiMethod()` is the likely culprit and causes some confusion as BreezSDK is not a singleton & has no instance management logic, which is not made clear on documentation. 

This will be handled on plugin itself but let's create a single instance of BreezSDK on `dart_snippets.dart::main()` and use it throughout the snippets temporarily.

**Comment by ok300** [comment]
Closed by #163?
