### ISSUE TITLE
Add a "Moving into production" section

### ISSUE THREAD

**Issue by dangeross** [breez/breez-sdk-docs#44]
It should outline: 
1. Who to contact to get a partner certificate.
2. How to set the NodeConfig with the received partner certificate & key.

**Comment by erdemyerebasmaz** [comment]
@dangeross, @kingonly has introduced [Moving to Production](https://sdk-doc.breez.technology/guide/production.html) in 6648604d3117219e3de38f7cd95c5e82750b7993 _bb7e24b9b0dad0557a911af162c865c7a00be577 5d220f67c54ada5b2da7b30e932cccfe052546ea_

If there are no other requirements, let's close this issue.

**Comment by dangeross** [comment]
I think it would be good to have a small example of how to pass the Greenlight partner certificate/key in the NodeConfig instead of an invite code. I'll write a PR.

**Comment by kingonly** [comment]
#2 isn't specified
